### ISSUE TITLE
`scale` transformation is limited to powers

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/desirability2#5]
I haven't read too much about desirability functions. But is there a reason why the scaling is limited to powers and not any order-preserving transformation that maps the region [0, 1] to [0, 1]?

**Comment by topepo** [comment]
A ton of different functions could be used. The ones used here are the most commonly used (from Derringer and Suich) but could be anything that goes from some arbitrary scale to [0, 1].
